//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kartverket.FinnPosisjon.no.geonorge.ws {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.geonorge.no/SKWS2/services/Tran", ConfigurationName="no.geonorge.ws.Tran")]
    public interface Tran {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.ngisssrws.sk.hosledata.no) of message sosiTransRequest does not match the default value (https://ws.geonorge.no/SKWS2/services/Tran)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(TranKoordSet))]
        Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransResponse sosiTrans(Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransResponse> sosiTransAsync(Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ssr2.ws.statkart.no")]
    public partial class TranInpData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TranInpKoordSet[] inpKoordSetsField;
        
        private int resSosiKoordSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TranInpKoordSet[] inpKoordSets {
            get {
                return this.inpKoordSetsField;
            }
            set {
                this.inpKoordSetsField = value;
                this.RaisePropertyChanged("inpKoordSets");
            }
        }
        
        /// <remarks/>
        public int resSosiKoordSys {
            get {
                return this.resSosiKoordSysField;
            }
            set {
                this.resSosiKoordSysField = value;
                this.RaisePropertyChanged("resSosiKoordSys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ssr2.ws.statkart.no")]
    public partial class TranInpKoordSet : TranKoordSet {
        
        private int kommuneNrField;
        
        /// <remarks/>
        public int kommuneNr {
            get {
                return this.kommuneNrField;
            }
            set {
                this.kommuneNrField = value;
                this.RaisePropertyChanged("kommuneNr");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TranResKoordSet))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TranInpKoordSet))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ssr2.ws.statkart.no")]
    public partial class TranKoordSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double hoydeField;
        
        private double nordField;
        
        private double ostField;
        
        private int sosiKoordSysField;
        
        /// <remarks/>
        public double hoyde {
            get {
                return this.hoydeField;
            }
            set {
                this.hoydeField = value;
                this.RaisePropertyChanged("hoyde");
            }
        }
        
        /// <remarks/>
        public double nord {
            get {
                return this.nordField;
            }
            set {
                this.nordField = value;
                this.RaisePropertyChanged("nord");
            }
        }
        
        /// <remarks/>
        public double ost {
            get {
                return this.ostField;
            }
            set {
                this.ostField = value;
                this.RaisePropertyChanged("ost");
            }
        }
        
        /// <remarks/>
        public int sosiKoordSys {
            get {
                return this.sosiKoordSysField;
            }
            set {
                this.sosiKoordSysField = value;
                this.RaisePropertyChanged("sosiKoordSys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ssr2.ws.statkart.no")]
    public partial class TranRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TranInpKoordSet[] inpKoordSetsField;
        
        private string meldingField;
        
        private bool okField;
        
        private TranResKoordSet[] resKoordSetsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TranInpKoordSet[] inpKoordSets {
            get {
                return this.inpKoordSetsField;
            }
            set {
                this.inpKoordSetsField = value;
                this.RaisePropertyChanged("inpKoordSets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string melding {
            get {
                return this.meldingField;
            }
            set {
                this.meldingField = value;
                this.RaisePropertyChanged("melding");
            }
        }
        
        /// <remarks/>
        public bool ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
                this.RaisePropertyChanged("ok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public TranResKoordSet[] resKoordSets {
            get {
                return this.resKoordSetsField;
            }
            set {
                this.resKoordSetsField = value;
                this.RaisePropertyChanged("resKoordSets");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ssr2.ws.statkart.no")]
    public partial class TranResKoordSet : TranKoordSet {
        
        private int errKodeField;
        
        private string errTekstField;
        
        /// <remarks/>
        public int errKode {
            get {
                return this.errKodeField;
            }
            set {
                this.errKodeField = value;
                this.RaisePropertyChanged("errKode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string errTekst {
            get {
                return this.errTekstField;
            }
            set {
                this.errTekstField = value;
                this.RaisePropertyChanged("errTekst");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sosiTrans", WrapperNamespace="http://ws.ngisssrws.sk.hosledata.no", IsWrapped=true)]
    public partial class sosiTransRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string brukerid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string passord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string aliasId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public Kartverket.FinnPosisjon.no.geonorge.ws.TranInpData inputData;
        
        public sosiTransRequest() {
        }
        
        public sosiTransRequest(string brukerid, string passord, string aliasId, Kartverket.FinnPosisjon.no.geonorge.ws.TranInpData inputData) {
            this.brukerid = brukerid;
            this.passord = passord;
            this.aliasId = aliasId;
            this.inputData = inputData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sosiTransResponse", WrapperNamespace="https://ws.geonorge.no/SKWS2/services/Tran", IsWrapped=true)]
    public partial class sosiTransResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public Kartverket.FinnPosisjon.no.geonorge.ws.TranRes sosiTransReturn;
        
        public sosiTransResponse() {
        }
        
        public sosiTransResponse(Kartverket.FinnPosisjon.no.geonorge.ws.TranRes sosiTransReturn) {
            this.sosiTransReturn = sosiTransReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TranChannel : Kartverket.FinnPosisjon.no.geonorge.ws.Tran, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranClient : System.ServiceModel.ClientBase<Kartverket.FinnPosisjon.no.geonorge.ws.Tran>, Kartverket.FinnPosisjon.no.geonorge.ws.Tran {
        
        public TranClient() {
        }
        
        public TranClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TranClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TranClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransResponse Kartverket.FinnPosisjon.no.geonorge.ws.Tran.sosiTrans(Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest request) {
            return base.Channel.sosiTrans(request);
        }
        
        public Kartverket.FinnPosisjon.no.geonorge.ws.TranRes sosiTrans(string brukerid, string passord, string aliasId, Kartverket.FinnPosisjon.no.geonorge.ws.TranInpData inputData) {
            Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest inValue = new Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest();
            inValue.brukerid = brukerid;
            inValue.passord = passord;
            inValue.aliasId = aliasId;
            inValue.inputData = inputData;
            Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransResponse retVal = ((Kartverket.FinnPosisjon.no.geonorge.ws.Tran)(this)).sosiTrans(inValue);
            return retVal.sosiTransReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransResponse> Kartverket.FinnPosisjon.no.geonorge.ws.Tran.sosiTransAsync(Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest request) {
            return base.Channel.sosiTransAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransResponse> sosiTransAsync(string brukerid, string passord, string aliasId, Kartverket.FinnPosisjon.no.geonorge.ws.TranInpData inputData) {
            Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest inValue = new Kartverket.FinnPosisjon.no.geonorge.ws.sosiTransRequest();
            inValue.brukerid = brukerid;
            inValue.passord = passord;
            inValue.aliasId = aliasId;
            inValue.inputData = inputData;
            return ((Kartverket.FinnPosisjon.no.geonorge.ws.Tran)(this)).sosiTransAsync(inValue);
        }
    }
}
